# This file is part of log_parser.
# https://github.com/adeelahmad/log_parser

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2022, Adeel Ahmad <230291+adeelahmad@users.noreply.github.com>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
